# Generated by Django 4.2 on 2023-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
